# pybricks blocks file:{"blocks":{"languageVersion":0,"blocks":[{"type":"blockGlobalSetup","id":"bjK,wS1MYO7aiYkFSwd{","x":0,"y":0,"deletable":false,"next":{"block":{"type":"variables_set_prime_hub","id":"M)O^*ey0M}p,o@r--g{=","extraState":{"optionLevel":0},"fields":{"VAR":{"id":"o6qnY]8!/Fh~_5A_V7Z]"}},"next":{"block":{"type":"variables_set_motor","id":"cpwYij*wrnMf}1aL^XFa","fields":{"VAR":{"id":"ia%0/yc=`Grnl?T9wfMJ"}},"inputs":{"PORT":{"shadow":{"type":"blockParametersPort","id":"N,@|/9VA^qBZ03.r2LVG","fields":{"NAME":"A"}}},"POSITIVE_DIRECTION":{"shadow":{"type":"blockParametersDirection","id":"q;bAk^+Sbaj7,j*p#bdP","fields":{"SELECTION":"Direction.CLOCKWISE"}}}}}}}}},{"type":"blockGlobalStart","id":"3tJe|AWl0baN(wH9a$@.","x":-5,"y":201,"deletable":false,"next":{"block":{"type":"blockPrint","id":"j,,T}?rBkaW$1v?olp4p","extraState":{"optionLevel":0},"inputs":{"TEXT0":{"shadow":{"type":"text","id":"!x5.0YiWya^`(y)yO5B8","fields":{"TEXT":"Hello, Pybricks 2!"}}}},"next":{"block":{"type":"blockMotorRun","id":"M-.@6dv+|oTyHDDU+=Br","extraState":{"optionLevel":1},"fields":{"METHOD":"MOTOR_RUN_FOR"},"inputs":{"VAR":{"shadow":{"type":"variables_get_motor_device","id":"|XOkrRv[cjz|{qyjt;6P","fields":{"VAR":{"id":"ia%0/yc=`Grnl?T9wfMJ","name":"motor 1","type":"Motor"}}}},"VALUE0":{"shadow":{"type":"unit_angularVelocity","id":"(7:pa|zKFIaPt9GS6b_t","fields":{"VALUE0":1.111111111111111e+26}}},"ANGLE":{"shadow":{"type":"unit_angle","id":"NhrN%kxfYi77wsgVb?P^","fields":{"VALUE0":100000}}},"THEN":{"shadow":{"type":"parameters_stop_4","id":"2?eyiti4sD`pl!BZ,#8/","fields":{"VALUE":"Stop.NONE"}}}},"next":{"block":{"type":"blockPrint","id":"pDpBSq0;t2=0VX|ZS$[-","extraState":{"optionLevel":0},"inputs":{"TEXT0":{"shadow":{"type":"text","id":"?3J={TM3/=Z-kI%,l^Jg","fields":{"TEXT":"Done, Pybricks!"}}}}}}}}}}}]},"variables":[{"name":"red","id":"}i[t`RT7?NHM[bE?,NgM","type":"ColorDef"},{"name":"orange","id":"r|vu,CWBDc2%ni)mg0QL","type":"ColorDef"},{"name":"yellow","id":"~#7!H:WOLj[jO$5lWHuE","type":"ColorDef"},{"name":"green","id":"z66`bn6rE)Dr+QK[K97!","type":"ColorDef"},{"name":"cyan","id":"+9[KPZ/e9j0uW_V`+SJs","type":"ColorDef"},{"name":"blue","id":"w6xI3wKTZW{CzjvnEmuz","type":"ColorDef"},{"name":"violet","id":"wE!7bR)-{a0FHmWkI[Xm","type":"ColorDef"},{"name":"magenta","id":"5b.c!b`?comC_VJ5_-(a","type":"ColorDef"},{"name":"white","id":"$3_QCSguockj0}~!U{?3","type":"ColorDef"},{"name":"none","id":"DS9^i)I+0jHX0faD628j","type":"ColorDef"},{"name":"prime hub","id":"o6qnY]8!/Fh~_5A_V7Z]","type":"PrimeHub"},{"name":"motor 1","id":"ia%0/yc=`Grnl?T9wfMJ","type":"Motor"}],"info":{"type":"pybricks","version":"2.0.0"},"workspaceOptions":{"scrollX":338.6346472591561,"scrollY":124.50647789361875,"scale":0.616298010126029}}
from pybricks.hubs import PrimeHub
from pybricks.parameters import Direction, Port, Stop
from pybricks.pupdevices import Motor

# Set up.
prime_hub = PrimeHub()
motor_1 = Motor(Port.A, Direction.CLOCKWISE)


# The main program starts here.
print('Hello, Pybricks 2!')
motor_1.run_angle(1.111111111111111e+26, 100000, Stop.NONE)
print('Done, Pybricks!')
