# pybricks blocks file:{"blocks":{"languageVersion":0,"blocks":[{"type":"blockGlobalSetup","id":"bjK,wS1MYO7aiYkFSwd{","x":150,"y":100,"deletable":false,"next":{"block":{"type":"variables_set_motor","id":"L)s?~G1UjnIo;a]VTPI-","fields":{"VAR":{"id":"DT@MqJqE]Me!vBqLBOR0"}},"inputs":{"PORT":{"shadow":{"type":"blockParametersPort","id":"WVzJP9vQ$elJ%KeS={D0","fields":{"NAME":"E"}}},"POSITIVE_DIRECTION":{"shadow":{"type":"blockParametersDirection","id":"d@S}#iZqHAYbM7?Vx^%R","fields":{"SELECTION":"Direction.CLOCKWISE"}}}}}}},{"type":"blockGlobalStart","id":"3tJe|AWl0baN(wH9a$@.","x":150,"y":300,"deletable":false,"next":{"block":{"type":"blockPrint","id":"j,,T}?rBkaW$1v?olp4p","extraState":{"optionLevel":0},"inputs":{"TEXT0":{"shadow":{"type":"text","id":"!x5.0YiWya^`(y)yO5B8","fields":{"TEXT":"Hello, Pybricks!"}}}},"next":{"block":{"type":"blockMotorRun","id":"PAHUz:vQL@lwF}-G[;}1","extraState":{"optionLevel":1},"fields":{"METHOD":"MOTOR_RUN_FOR"},"inputs":{"VAR":{"shadow":{"type":"variables_get_motor_device","id":"O!yFJY)NZ}sl-]uMQrcK","fields":{"VAR":{"id":"DT@MqJqE]Me!vBqLBOR0","name":"right attachment","type":"Motor"}}}},"VALUE0":{"shadow":{"type":"unit_angularVelocity","id":"8[`tLu{C^.,u1gBJuP0P","fields":{"VALUE0":1000}}},"ANGLE":{"shadow":{"type":"unit_angle","id":"Cip#NaCJ_BFbu$IKzPTy","fields":{"VALUE0":3000}}},"THEN":{"shadow":{"type":"parameters_stop_4","id":".[Og*~c}ogTmyrt?T`L/","fields":{"VALUE":"Stop.HOLD"}}}},"next":{"block":{"type":"blockPrint","id":"$$-;JuZAvQ$i$*)(Z%4r","extraState":{"optionLevel":0},"inputs":{"TEXT0":{"shadow":{"type":"text","id":"AS0hXg2rN/fXKC6tfOb9","fields":{"TEXT":"uctyc"}}}}}}}}}}}]},"variables":[{"name":"red","id":"!4zI@1-vc5OTl$S#k+|;","type":"ColorDef"},{"name":"orange","id":"OpB@Rd(Up=/Kw+d2K7si","type":"ColorDef"},{"name":"yellow","id":"{EqazYXGfS=K)Q){jrXo","type":"ColorDef"},{"name":"green","id":"3c!NT_!1vT%v=e@^K#q8","type":"ColorDef"},{"name":"cyan","id":"SDrp6MaEm=Xcc}fwFy{c","type":"ColorDef"},{"name":"blue","id":"YW{I~#_T*l=/:KEnka7x","type":"ColorDef"},{"name":"violet","id":"iI}S3{1:%u[%h7nUeZY[","type":"ColorDef"},{"name":"magenta","id":"Ugsby94AcF#NFMjcY~lA","type":"ColorDef"},{"name":"white","id":"N{81e^OS`_!CEN?SkIc/","type":"ColorDef"},{"name":"none","id":"mO2$j2~mF08iiQ[mWC#:","type":"ColorDef"},{"name":"right attachment","id":"DT@MqJqE]Me!vBqLBOR0","type":"Motor"}],"info":{"type":"pybricks","version":"2.0.0"},"workspaceOptions":{"scrollX":338.42005351429543,"scrollY":94.11446043191623,"scale":0.5851687612169532}}
from pybricks.parameters import Direction, Port, Stop
from pybricks.pupdevices import Motor

# Set up.
right_attachment = Motor(Port.E, Direction.CLOCKWISE)


# The main program starts here.
print('Hello, Pybricks!')
right_attachment.run_angle(1000, 3000)
print('uctyc')
